"""Initial migration with user and system models

Revision ID: 400ac13b96f8
Revises: 
Create Date: 2026-01-08 08:11:51.986488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400ac13b96f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_systems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_systems_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('user_business_system',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_system_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_system_id'], ['business_systems.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'business_system_id')
    )
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('os_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('business_system_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'business_systems', ['business_system_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('business_system_id')
        batch_op.drop_column('os_type')

    op.drop_table('user_business_system')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('business_systems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_systems_name'))

    op.drop_table('business_systems')
    # ### end Alembic commands ###
