"""Add content columns to DirectoryDiffResult

Revision ID: 84b05afd2b57
Revises: 936b1bb90537
Create Date: 2026-01-09 17:55:23.702731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84b05afd2b57'
down_revision = '936b1bb90537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('directory_diff_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('left_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('right_content', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('directory_diff_results', schema=None) as batch_op:
        batch_op.drop_column('right_content')
        batch_op.drop_column('left_content')

    # ### end Alembic commands ###
