"""Add ScheduledTask model

Revision ID: 936b1bb90537
Revises: 400ac13b96f8
Create Date: 2026-01-08 16:21:14.098657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '936b1bb90537'
down_revision = '400ac13b96f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('run_time', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_config_maps',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('config_map_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['config_map_id'], ['config_maps.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['scheduled_tasks.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'config_map_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_config_maps')
    op.drop_table('scheduled_tasks')
    # ### end Alembic commands ###
