"""Change DirectoryDiffResult content columns to LONGTEXT

Revision ID: f639587debf3
Revises: 84b05afd2b57
Create Date: 2026-01-09 21:27:21.795946

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f639587debf3'
down_revision = '84b05afd2b57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('directory_diff_results', schema=None) as batch_op:
        batch_op.alter_column('diff_content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
        batch_op.alter_column('left_content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
        batch_op.alter_column('right_content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('directory_diff_results', schema=None) as batch_op:
        batch_op.alter_column('right_content',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('left_content',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('diff_content',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)

    # ### end Alembic commands ###
